version: '3.3'

services:

  ui:
    image: benjaminslabbert/trak_ui:latest
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./.data/db_mongo:/data/db
    ports:
      - 27017:27017
