version: '2.2'

services:

  rabbit:
    image: rabbitmq
    hostname: rabbit
    restart: always
    mem_limit: 600m
    ports:
      - 5672:5672
    volumes:
      - rabbit-data:/var/lib/rabbitmq

  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 6379:6379
    mem_limit: 600m
    volumes:
      - redis-data:/data

  rds:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - rds-data:/var/lib/mysql
    mem_limit: 600m
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=trak
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  engine:
    image: benjaminslabbert/trak_engine:1.0.0
    restart: always
    mem_limit: 600m
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - rds
      - rabbit

  worker:
    image: benjaminslabbert/trak_worker:1.0.0
    restart: always
    mem_limit: 600m
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - rds
      - rabbit
      - engine

  search:
    image: benjaminslabbert/trak_search:1.0.0
    restart: always
    mem_limit: 250m
    ports:
      - 50052:50052
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - rds
      - rabbit
      - es

  api:
    image: benjaminslabbert/trak_api:1.0.0
    restart: always
    mem_limit: 250m
    ports:
      - 50051:50051
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - rds
      - rabbit

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "transport.host=es"

  logstash:
    image: benjaminslabbert/trak_logstash:1.0.0
    ports:
      - 9600:9600
    restart: always
    depends_on:
      - es

volumes:
  rabbit-data:
    driver: local
  rds-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local
